config/routes.rb
Rails.application.routes.draw do
  resources :preimpresos

  resources :subagencias do
    resources :impresos
  end

  resources :agencias
  # resources :subagencias
  resources :subagencias do
    resources :juegos_impreso
  end
  resources :sessions, only: [:new, :create, :destroy]

  root 'static_pages#home'
  match '/registro', to: 'agencias#new', via: 'get'
  match '/home', to: 'agencias#home', via: 'get'
  match '/login', to: 'sessions#new', via: 'get'
  match '/logout', to: 'sessions#destroy', via: 'delete'
  match '/listado', to: 'subagencias#index', via: 'get'

end

app/models/preimpreso.rb
class Preimpreso < ActiveRecord::Base
  belongs_to :agencia
  enum tipo:  [:telekino, :maradona, :telebingo]
end

app/controllers/preimpresos_controller.rb
class PreimpresosController < ApplicationController
  before_action :set_preimpreso, only: [:show, :edit, :update, :destroy]

  # GET /preimpresos
  # GET /preimpresos.json
  def index
    @preimpresos = Preimpreso.all
  end

  # GET /preimpresos/1
  # GET /preimpresos/1.json
  def show
  end

  # GET /preimpresos/new
  def new
    @preimpreso = current_agencia.preimpresos.build
  end

  # GET /preimpresos/1/edit
  def edit
  end

  # POST /preimpresos
  # POST /preimpresos.json
  def create
    @preimpreso = Preimpreso.new(preimpreso_params)

    respond_to do |format|
      if @preimpreso.save
        format.html { redirect_to @preimpreso, notice: 'Preimpreso was successfully created.' }
        format.json { render :show, status: :created, location: @preimpreso }
      else
        format.html { render :new }
        format.json { render json: @preimpreso.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /preimpresos/1
  # PATCH/PUT /preimpresos/1.json
  def update
    respond_to do |format|
      if @preimpreso.update(preimpreso_params)
        format.html { redirect_to @preimpreso, notice: 'Preimpreso was successfully updated.' }
        format.json { render :show, status: :ok, location: @preimpreso }
      else
        format.html { render :edit }
        format.json { render json: @preimpreso.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /preimpresos/1
  # DELETE /preimpresos/1.json
  def destroy
    @preimpreso.destroy
    respond_to do |format|
      format.html { redirect_to preimpresos_url, notice: 'Preimpreso was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_preimpreso
      @preimpreso = Preimpreso.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def preimpreso_params
      params.require(:preimpreso).permit(:fecha_sorteo, :fecha_inicio, :numero_sorteo, :precio, :cantidad, :tipo, :devolucion, :agencia_id)
    end
end

app/helpers/preimpresos_helper.rb
module PreimpresosHelper
end

app/views/preimpresos/_form.html.erb
<div class="form-panel">
  <%= form_for(@preimpreso) do |f| %>
    <% if @preimpreso.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@preimpreso.errors.count, "error") %> prohibited this preimpreso from being saved:</h2>

        <ul>
        <% @preimpreso.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :fecha_sorteo %><br>
      <%= f.date_select :fecha_sorteo %>
    </div>
    <div class="field">
      <%= f.label :fecha_inicio %><br>
      <%= f.date_select :fecha_inicio %>
    </div>
    <div class="field">
      <%= f.label :numero_sorteo %><br>
      <%= f.number_field :numero_sorteo %>
    </div>
    <div class="field">
      <%= f.label :precio %><br>
      <%= f.text_field :precio %>
    </div>
    <div class="field">
      <%= f.label :cantidad %><br>
      <%= f.number_field :cantidad %>
    </div>
    <div class="field">
      <%= f.select :tipo, Preimpreso.tipos.keys.to_a %>


    </div>
    <div class="field">
      <%= f.label :devolucion %><br>
      <%= f.number_field :devolucion %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/preimpresos/edit.html.erb
<h1>Editing preimpreso</h1>

<%= render 'form' %>

<%= link_to 'Show', @preimpreso %> |
<%= link_to 'Back', preimpresos_path %>

app/views/preimpresos/index.html.erb
<section id="main-content">

  <section class="wrapper site-min-height">
    <!-- /.col-lg-12 -->
    <div class="row mt">
      <div class="col-lg-12">
        <div class="content-panel">
          <h4>Listado de juegos preimpresos</h4>
            <section id="unseen">
              <table class="table table-striped table-bordered table-condensed">
                <thead>
                  <tr>
                    <th>Fecha sorteo</th>
                    <th>Fecha inicio</th>
                    <th>Numero sorteo</th>
                    <th>Precio</th>
                    <th>Cantidad</th>
                    <th>Tipo</th>
                    <th>Devolucion</th>
                    <th>Agencia</th>
                    <th colspan="3"></th>
                  </tr>
                </thead>

                <tbody>
                  <% @preimpresos.each do |preimpreso| %>
                    <tr>
                      <td><%= preimpreso.fecha_sorteo %></td>
                      <td><%= preimpreso.fecha_inicio %></td>
                      <td><%= preimpreso.numero_sorteo %></td>
                      <td><%= preimpreso.precio %></td>
                      <td><%= preimpreso.cantidad %></td>
                      <td><%= preimpreso.tipo %></td>
                      <td><%= preimpreso.devolucion %></td>
                      <td><%= preimpreso.agencia %></td>
                      <td><%= link_to 'Show', preimpreso %></td>
                      <td><%= link_to 'Edit', edit_preimpreso_path(preimpreso) %></td>
                      <td><%= link_to 'Destroy', preimpreso, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
<%= link_to 'New Preimpreso', new_preimpreso_path %>
            </section>
          </div>
        </div>
      </div>
    </section>

  </section>

app/views/preimpresos/new.html.erb
<section id="main-content">
  <section class="wrapper">
    <h3><i class="fa fa-angle-right"></i>Nuevo juego preimpreso</h3>
      <div class="row mt">
        <div class="col-lg-12">

            <%= render 'form' %>

<%= link_to 'Volver', preimpresos_path %>
      </div>
    </div>
  </section>
</section>

app/views/preimpresos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fecha sorteo:</strong>
  <%= @preimpreso.fecha_sorteo %>
</p>

<p>
  <strong>Fecha inicio:</strong>
  <%= @preimpreso.fecha_inicio %>
</p>

<p>
  <strong>Numero sorteo:</strong>
  <%= @preimpreso.numero_sorteo %>
</p>

<p>
  <strong>Precio:</strong>
  <%= @preimpreso.precio %>
</p>

<p>
  <strong>Cantidad:</strong>
  <%= @preimpreso.cantidad %>
</p>

<p>
  <strong>Tipo:</strong>
  <%= @preimpreso.tipo %>
</p>

<p>
  <strong>Devolucion:</strong>
  <%= @preimpreso.devolucion %>
</p>

<p>
  <strong>Agencia:</strong>
  <%= @preimpreso.agencia %>
</p>

<%= link_to 'Edit', edit_preimpreso_path(@preimpreso) %> |
<%= link_to 'Back', preimpresos_path %>