config/routes.rb
Rails.application.routes.draw do
  resources :preimpresos

  resources :subagencias do
    resources :impresos
  end

  resources :agencias
  # resources :subagencias
  resources :subagencias do
    resources :juegos_impreso
  end
  resources :sessions, only: [:new, :create, :destroy]

  root 'static_pages#home'
  match '/registro', to: 'agencias#new', via: 'get'
  match '/home', to: 'agencias#home', via: 'get'
  match '/login', to: 'sessions#new', via: 'get'
  match '/logout', to: 'sessions#destroy', via: 'delete'
  match '/listado', to: 'subagencias#index', via: 'get'

end

app/models/impreso.rb
class Impreso < ActiveRecord::Base
  belongs_to :subagencia

  validates :quiniela, presence: true
end

app/controllers/impresos_controller.rb
class ImpresosController < ApplicationController
  before_action :set_impreso, only: [:show, :edit, :update, :destroy]

  # GET /impresos
  # GET /impresos.json
  def index
    @subagencia = Subagencia.find(params[:subagencia_id])
    @impresos = @subagencia.impresos.order(:fecha)
  end

  # GET /impresos/1
  # GET /impresos/1.json
  def show
  end

  # GET /impresos/new
  def new
    @subagencia = Subagencia.find(params[:subagencia_id])
    @impreso = @subagencia.impresos.build
  end

  # GET /impresos/1/edit
  def edit
  end

  # POST /impresos
  # POST /impresos.json
  def create
    @subagencia = Subagencia.find(params[:subagencia_id])
    @impreso = @subagencia.impresos.build(impreso_params)

    respond_to do |format|
      if @impreso.save
        format.html { redirect_to subagencia_impresos_url(@subagencia), notice: 'Juego impreso fue guardado.' }
        format.json { render :show, status: :created, location: @impreso }
      else
        format.html { render :new }
        format.json { render json: @impreso.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /impresos/1
  # PATCH/PUT /impresos/1.json
  def update
    respond_to do |format|
      if @impreso.update(impreso_params)
        format.html { redirect_to @impreso, notice: 'Juego impreso fue actualizado.' }
        format.json { render :show, status: :ok, location: @impreso }
      else
        format.html { render :edit }
        format.json { render json: @impreso.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /impresos/1
  # DELETE /impresos/1.json
  def destroy
    @impreso.destroy
    respond_to do |format|
      format.html { redirect_to subagencia_impresos_url(@impreso.subagencia), notice: 'Juego impreso fue eliminado' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_impreso
      @subagencia = Subagencia.find(params[:subagencia_id])
      @impreso = @subagencia.impresos.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def impreso_params
      params.require(:impreso).permit(:fecha, :quiniela, :quini_ex, :loteria_online, :otros_juegos, :otros_gastos, :premios)
    end
end

app/helpers/impresos_helper.rb
module ImpresosHelper
end

app/views/impresos/_form.html.erb
<div class="form-panel">
  <%= form_for [@impreso.subagencia, @impreso] do |f| %>
  <%#= render 'shared/error_messages', object: f.object %>
  <%#= f.hidden_field :subagencia_id , :value=>params[:subagencia_id] %>
  <% if @impreso.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@impreso.errors.count, "error") %> prohibited this impreso from being saved:</h2>

      <ul>
      <% @impreso.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="form-group">
      <%= f.label :fecha %><br>
      <%= f.date_select :fecha %>
    </div>

    <div class="form-group">
      <%= f.label :quiniela %>
      <%= f.number_field :quiniela, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :quini_express %>
      <%= f.number_field :quini_ex, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :loteria_online %>
      <%= f.number_field :loteria_online, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :otros_juegos %>
      <%= f.number_field :otros_juegos, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :otros_gastos %>
      <%= f.number_field :otros_gastos, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :premios %>
      <%= f.text_field :premios, class: "form-control" %>
    </div>

    <%= f.submit "Guardar", class: "btn btn-default btn-lg btn-primary" %>
  <% end %>
</div>

app/views/impresos/edit.html.erb
<h1>Editing impreso</h1>

<%= render 'form' %>

<%= link_to 'Show', @impreso %> |
<%= link_to 'Back', impresos_path %>

app/views/impresos/index.html.erb
<% provide(:title, "Juegos impresos") %>

  <section id="main-content">

    <section class="wrapper site-min-height">
      <!-- /.col-lg-12 -->
      <div class="row mt">
        <div class="col-lg-12">
          <div class="content-panel">
            <h4>Listado de juegos impresos</h4>
              <section id="unseen">
                <table class="table table-striped table-bordered table-condensed">
                  <thead>
                    <tr>
                      <th>Fecha</th>
                      <th>Quiniela</th>
                      <th>Quini ex</th>
                      <th>Loteria online</th>
                      <th>Otros juegos</th>
                      <th>Otros gastos</th>
                      <th>Premios</th>
                      <th>Subagencia</th>
                      <th>Total</th>
                      <th colspan="3"></th>
                    </tr>
                  </thead>

                  <tbody>
                    <% fecha = @impresos.first.fecha %>
                    <% comision_quiniela = 0 %>
                    <% comision_quiniela_desc = 0 %>
                    <% comision_express = 0 %>
                    <% comision_express_desc = 0 %>
                    <% comision_loteria = 0 %>
                    <% comision_loteria_desc = 0 %>
                    <% comision_juegos = 0 %>
                    <% comision_juegos_desc = 0 %>

                    <% @impresos.each do |impreso| %>

                      <% if fecha != impreso.fecha  %>
                        <tr class="info">
                          <td>total neto</td>
                          <td><%= comision_quiniela %></td>
                          <td><%= comision_express %></td>
                          <td><%= comision_loteria %></td>
                          <td><%= comision_juegos %></td>
                          <td></td>
                          <td></td>
                          <td></td>
                          <td></td>
                          <td></td>
                          <td></td>
                        </tr>
                        <tr class="info">
                          <td>con descuento</td>
                          <td><%= comision_quiniela_desc %></td>
                          <td><%= comision_express_desc %></td>
                          <td><%= comision_loteria_desc %></td>
                          <td><%= comision_juegos_desc %></td>
                          <td></td>
                          <td></td>
                          <td></td>
                          <td></td>
                          <td></td>
                          <td></td>
                        </tr>

                        <% comision_quiniela = 0 %>
                        <% fecha = impreso.fecha %>
                      <% end %>

                      <% total_quiniela = impreso.quiniela - (impreso.quiniela * 15 /  100) %>
                      <% total_express = impreso.quini_ex - (impreso.quini_ex * 8 /  100) %>
                      <% total_loteria = impreso.loteria_online - (impreso.loteria_online * 16 /  100) %>
                      <% total_juegos = impreso.otros_juegos - (impreso.otros_juegos * 10 /  100) %>
                      <% total = (total_quiniela + total_express + total_loteria + total_juegos + impreso.otros_gastos) - impreso.premios %>

                      <% comision_quiniela += impreso.quiniela %>
                      <% comision_express += impreso.quini_ex %>
                      <% comision_loteria += impreso.loteria_online %>
                      <% comision_juegos += impreso.otros_juegos %>

                      <% comision_quiniela_desc += total_quiniela %>
                      <% comision_express_desc += total_express %>
                      <% comision_loteria_desc += total_loteria %>
                      <% comision_juegos_desc += total_juegos %>



                      <tr>
                        <td><%= impreso.fecha %></td>
                        <td><%= impreso.quiniela %></td>
                        <td><%= impreso.quini_ex %></td>
                        <td><%= impreso.loteria_online %></td>
                        <td><%= impreso.otros_juegos %></td>
                        <td><%= impreso.otros_gastos %></td>
                        <td><%= impreso.premios %></td>
                        <td><%= impreso.subagencia.numero_subagencia %></td>
                        <td><%= total %></td>
                        <td><%= link_to 'Ver', [impreso.subagencia, impreso] %></td>
                        <td><%= link_to 'Eliminar', [impreso.subagencia, impreso], method: :delete, data: { confirm: 'Are you sure?' } %></td>
                      </tr>

                    <% end %>
                    <tr class="info">
                      <td>total neto</td>
                      <td><%= comision_quiniela %></td>
                      <td><%= comision_express %></td>
                      <td><%= comision_loteria %></td>
                      <td><%= comision_juegos %></td>
                      <td></td>
                      <td></td>
                      <td></td>
                      <td></td>
                      <td></td>
                      <td></td>
                    </tr>
                    <tr class="info">
                      <td>con descuento</td>
                      <td><%= comision_quiniela_desc %></td>
                      <td><%= comision_express_desc %></td>
                      <td><%= comision_loteria_desc %></td>
                      <td><%= comision_juegos_desc %></td>
                      <td></td>
                      <td></td>
                      <td></td>
                      <td></td>
                      <td></td>
                      <td></td>
                    </tr>
                  </tbody>
                </table>
              </section>
            </div>
          </div>
        </div>
      </section>

    </section>

app/views/impresos/new.html.erb
<section id="main-content">
  <section class="wrapper">
    <h3><i class="fa fa-angle-right"></i>Nuevo juego impreso</h3>
      <div class="row mt">
        <div class="col-lg-12">

            <%= render 'form' %>

<%= link_to 'Volver', subagencia_impresos_path(@impreso.subagencia) %>
      </div>
    </div>
  </section>
</section>

app/views/impresos/show.html.erb
<section id="main-content">
  <section class="wrapper site-min-height">
    <div class="row">
      <div class="col-lg-12">

        <p>
          <strong>Fecha:</strong>
          <%= @impreso.fecha %>
        </p>

        <p>
          <strong>Quiniela:</strong>
          <%= @impreso.quiniela %>
        </p>

        <p>
          <strong>Quini ex:</strong>
          <%= @impreso.quini_ex %>
        </p>

        <p>
          <strong>Loteria online:</strong>
          <%= @impreso.loteria_online %>
        </p>

        <p>
          <strong>Otros juegos:</strong>
          <%= @impreso.otros_juegos %>
        </p>

        <p>
          <strong>Otros gastos:</strong>
          <%= @impreso.otros_gastos %>
        </p>

        <p>
          <strong>Premios:</strong>
          <%= @impreso.premios %>
        </p>

        <p>
          <strong>Subagencia:</strong>
          <%= @impreso.subagencia.numero_subagencia %>
        </p>

        <%= link_to 'Edit', edit_subagencia_impreso_path(@impreso.subagencia, @impreso) %> |

      </div>
    </div>
  </section>
</section>