config/routes.rb
Rails.application.routes.draw do
  resources :preimpresos

  resources :subagencias do
    resources :impresos
  end

  resources :agencias
  # resources :subagencias
  resources :subagencias do
    resources :juegos_impreso
  end
  resources :sessions, only: [:new, :create, :destroy]

  root 'static_pages#home'
  match '/registro', to: 'agencias#new', via: 'get'
  match '/home', to: 'agencias#home', via: 'get'
  match '/login', to: 'sessions#new', via: 'get'
  match '/logout', to: 'sessions#destroy', via: 'delete'
  match '/listado', to: 'subagencias#index', via: 'get'

end

app/views/shared/_aside.html.erb
<aside>
    <div id="sidebar"  class="nav-collapse ">
        <!-- sidebar menu start-->
        <ul class="sidebar-menu" id="nav-accordion">

            <p class="centered"><a href="profile.html">
            <%= image_tag "ui-sam.jpg", class: "img-circle", width: "60" %>
            </a></p>
            <% if current_agencia %>
              <h5 class="centered"> <%= current_agencia.titular %> </h5>
            <% end %>

            <li class="mt">
                <%= link_to listado_path do %>
                    <i class="fa fa-bar-chart-o"></i>
                    <span>Contabilidad Diaria</span>
                <% end %>
            </li>

            <li class="sub-menu">
                <a href="" >
                    <i class="fa fa-desktop"></i>
                    <span>Juegos Preimpresos</span>
                </a>
                <ul class="sub">
                    <li><%= link_to "Nuevo preimpreso", new_preimpreso_path %></li>
                    <!-- <li><a href="">De subagencia</a></li> -->
                </ul>
            </li>

            <li class="sub-menu">
                <a href="" >
                    <i class="fa fa-cogs"></i>
                    <span>Subagencias</span>
                </a>
                <ul class="sub">
                    <li>
                      <%= link_to "Listado", subagencias_path %>
                    </li>
                    <li>
                      <%= link_to "Agregar", new_subagencia_path %>
                    </li>
                </ul>
            </li>
            <!-- <li class="sub-menu">
                <a class="" href="javascript:;" >
                    <i class="fa fa-book"></i>
                    <span>Comision por venta</span>
                </a>
            </li> -->
            <li class="sub-menu">
                <%= link_to current_agencia do %>
                    <i class="fa fa-gear fa-fw"></i>
                    <span>Cuenta de usuario</span>
                <% end %>
            </li>

        </ul>
        <!-- sidebar menu end-->
    </div>
</aside>
<!--sidebar end-->

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <strong>
        The form contains
        <%= pluralize(object.errors.count, "error") %>.</strong>
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li>*
          <%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for(type) %> alert-dismissable fade in">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <%= message %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<header class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">Inicio</a>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-right navbar-ex1-collapse">
      <ul class="nav navbar-nav">
        <li><a href="#">Acerca</a>
        </li>
        <li><%= link_to 'Registrarse', registro_path %>
        </li>
        <li>
          <%= link_to 'Iniciar Sesion', login_path %>
        </li>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container -->
</header>

app/views/shared/_navigation.html.erb
<header class="header black-bg">
        <div class="sidebar-toggle-box">
            <div class="fa fa-bars tooltips" data-placement="right" data-original-title="Toggle Navigation"></div>
        </div>
      <!--logo start-->
      <%= link_to home_path, class: "logo" do %>
        <b>Proyecto Agencia</b>
      <% end %>
      <!--logo end-->
      <div class="nav notify-row" id="top_menu">
          <!--  notification start -->
          <ul class="nav top-menu">
              <!-- settings start -->

              <!-- settings end -->
              <!-- inbox dropdown start-->
              <!-- <li id="header_inbox_bar" class="dropdown">
                  <a data-toggle="dropdown" class="dropdown-toggle" href="index.html#">
                      <i class="fa fa-envelope-o"></i>
                      <span class="badge bg-theme">5</span>
                  </a>
                  <ul class="dropdown-menu extended inbox">
                      <div class="notify-arrow notify-arrow-green"></div>
                      <li>
                          <p class="green">You have 5 new messages</p>
                      </li>
                      <li>
                          <a href="index.html#">
                              <span class="photo"><img alt="avatar" src="assets/img/ui-zac.jpg"></span>
                              <span class="subject">
                              <span class="from">Zac Snider</span>
                              <span class="time">Just now</span>
                              </span>
                              <span class="message">
                                  Hi mate, how is everything?
                              </span>
                          </a>
                      </li>
                      <li>
                          <a href="index.html#">
                              <span class="photo"><img alt="avatar" src="assets/img/ui-divya.jpg"></span>
                              <span class="subject">
                              <span class="from">Divya Manian</span>
                              <span class="time">40 mins.</span>
                              </span>
                              <span class="message">
                               Hi, I need your help with this.
                              </span>
                          </a>
                      </li>
                      <li>
                          <a href="index.html#">
                              <span class="photo"><img alt="avatar" src="assets/img/ui-danro.jpg"></span>
                              <span class="subject">
                              <span class="from">Dan Rogers</span>
                              <span class="time">2 hrs.</span>
                              </span>
                              <span class="message">
                                  Love your new Dashboard.
                              </span>
                          </a>
                      </li>
                      <li>
                          <a href="index.html#">
                              <span class="photo"><img alt="avatar" src="assets/img/ui-sherman.jpg"></span>
                              <span class="subject">
                              <span class="from">Dj Sherman</span>
                              <span class="time">4 hrs.</span>
                              </span>
                              <span class="message">
                                  Please, answer asap.
                              </span>
                          </a>
                      </li>
                      <li>
                          <a href="index.html#">See all messages</a>
                      </li>
                  </ul>
              </li> -->
              <!-- inbox dropdown end -->
          </ul>
          <!--  notification end -->
      </div>
      <div class="top-menu">
        <ul class="nav pull-right top-menu">
          <li>
            <%= link_to "Salir", logout_path, class: "logout", method: "delete" %>
          </li>
        </ul>
      </div>
  </header>