config/routes.rb
Rails.application.routes.draw do
  resources :preimpresos

  resources :subagencias do
    resources :impresos
  end

  resources :agencias
  # resources :subagencias
  resources :subagencias do
    resources :juegos_impreso
  end
  resources :sessions, only: [:new, :create, :destroy]

  root 'static_pages#home'
  match '/registro', to: 'agencias#new', via: 'get'
  match '/home', to: 'agencias#home', via: 'get'
  match '/login', to: 'sessions#new', via: 'get'
  match '/logout', to: 'sessions#destroy', via: 'delete'
  match '/listado', to: 'subagencias#index', via: 'get'

end

app/models/subagencia.rb
class Subagencia < ActiveRecord::Base
  belongs_to :agencia
  has_many :juegos_impreso
  has_many :impresos

  validates :numero_subagencia, presence: true
  validates :email, presence: true
  validates :titular, presence: true
  validates :domicilio, presence: true
  validates :telefono, presence: true
end

app/controllers/subagencias_controller.rb
class SubagenciasController < ApplicationController
  before_action :signed_in_agencia
  before_action :set_subagencia, only: [:show, :edit, :update, :destroy]

  def index
    @subagencias = current_agencia.subagencias
  end

  # def listado
  #   @subagencias = current_agencia.subagencias
  # end

  def new
    @subagencia = current_agencia.subagencias.build
  end

  def create
    @subagencia = current_agencia.subagencias.build(subagencia_params)
    if @subagencia.save
      flash[:success] = 'Agregada Subagencia'
      redirect_to home_url
    else
      render 'new'
    end
  end

  def show
    @impreso = @subagencia.impresos.build
  end

  def edit
  end

  def update
    if @subagencia.update(subagencia_params)
        redirect_to @subagencia, notice: 'La subagencia fue actualizada'
    else
      render 'edit'
    end
  end

  private

    def set_subagencia
      @subagencia = Subagencia.find(params[:id])
    end

    def subagencia_params
      params.require(:subagencia).permit(:titular, :numero_subagencia, :email,
                                  :telefono, :domicilio)
    end
end

app/helpers/subagencias_helper.rb
module SubagenciasHelper
end

app/views/subagencias/edit.html.erb
<section id="main-content">
  <section class="wrapper site-min-height">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <h2>Editar Subagencia <%= @subagencia.numero_subagencia %></h2>

        <%= form_for @subagencia do |f| %>
          <%= render 'shared/error_messages', object: f.object %>

          <div class="form-group">
            <%= f.label :titular %>
            <%= f.text_field :titular, class: "form-control" %>
          </div>

          <div class="form-group">
            <%= f.label :numero_subagencia %>
            <%= f.text_field :numero_subagencia, class: "form-control" %>
          </div>

          <div class="form-group">
          <%= f.label :email %>
          <%= f.text_field :email, class: "form-control" %>
          </div>

          <div class="form-group">
            <%= f.label :telefono %>
            <%= f.text_field :telefono, class: "form-control" %>
          </div>

          <div class="form-group">
            <%= f.label :domicilio %>
            <%= f.text_field :domicilio, class: "form-control" %>
          </div>

          <%= f.submit "Guardar Cambios", class: "btn btn-default btn-lg btn-primary" %>
        <% end %>
      </div>
    </div>
  </section>
</section>

app/views/subagencias/index.html.erb
<% provide(:title, "Listado Subagencias") %>

  <section id="main-content">

    <section class="wrapper site-min-height">
        <h3><i class="fa fa-angle-right"></i>Listado de subagencias</h3>
      <!-- /.col-lg-12 -->
      <div class="row mt">
        <div class="col-lg-12">
          <div class="content-panel">
            <h4>Listado de subagencias</h4>
              <section id="unseen">
              <table class="table table-striped table-bordered table-condensed">
                <thead>
                  <tr>
                    <th>#</th>
                    <th>Titular</th>
                    <th>Domicilio</th>
                    <th>Ver</th>
                    <th>Modificar</th>
                  </tr>
                </thead>
                <tbody>
                  <% @subagencias.each do |s|%>
                    <tr>
                      <td><%= s.numero_subagencia %></td>
                      <td><%= s.titular %></td>
                      <td><%= s.domicilio %></td>
                      <td><a href="<%= subagencia_path(s) %>">Ir</a></td>
                      <td><%= link_to("Editar", edit_subagencia_path(s)) %>
                      </td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </section>
          </div>
        </div>
      </div>
    </section>

  </section>

app/views/subagencias/listado.html.erb
<% provide(:title, "Listado Subagencias") %>
<div id="wrapper">
  <%= render 'agencias/navigation' %>
  <div id="page-wrapper">
    <div class="row">
      <div class="col-lg-12">
        <h1 class="page-header">Subagencias</h1>
      </div>
      <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
    <div class="row">
      <div class="col-lg-12">
        <div class="panel panel-default">
          <div class="panel-heading">Listado de subagencias</div>
          <div class="panel-body">
            <div class="table-responsive">
              <table class="table table-striped table-bordered table-hover">
                <thead>
                  <tr>
                    <th>#</th>
                    <th>Titular</th>
                    <th>Domicilio</th>
                    <th>Elegir</th>
                  </tr>
                </thead>
                <tbody>
                  <% @subagencias.each do |s|%>
                    <tr>
                      <td><%= s.numero_subagencia %></td>
                      <td><%= s.titular %></td>
                      <td><%= s.domicilio %></td>
                      <td><a href="<%= subagencia_path s %>">Ir</a></td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!--/ .row -->
  </div>
  <!-- /#page-wrapper -->
</div>

app/views/subagencias/new.html.erb
<section id="main-content">
  <section class="wrapper">

      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <h2>Nueva Subagencia</h2>

          <div class="form-panel">
            <%= form_for @subagencia, :url => subagencias_path do |f| %>
              <%= render 'shared/error_messages', object: f.object %>

                <div class="form-group">
                  <%= f.label :titular %>
                  <%= f.text_field :titular, class: "form-control" %>
                </div>

                <div class="form-group">
                  <%= f.label :numero_subagencia %>
                  <%= f.text_field :numero_subagencia, class: "form-control" %>
                </div>

                <div class="form-group">
                  <%= f.label :email %>
                  <%= f.text_field :email, class: "form-control" %>
                </div>

                <div class="form-group">
                  <%= f.label :telefono %>
                  <%= f.text_field :telefono, class: "form-control" %>
                </div>

                <div class="form-group">
                  <%= f.label :domicilio %>
                  <%= f.text_field :domicilio, class: "form-control" %>
                </div>

                <%= f.submit "Agregar subagencia", class: "btn btn-default btn-lg btn-primary" %>
              <% end %>
          </div>

        </div>
      </div>

  </section>
</section>

app/views/subagencias/show.html.erb
<% provide(:title, "Listado Subagencias") %>

  <section id="main-content">
    <section class="wrapper site-min-height">
      <div class="row">
        <div class="col-lg-12">
          <h1 class="page-header">Subagencia <%= @subagencia.numero_subagencia %></h1>
            <p>Titular:
              <%= @subagencia.titular %></p>
            <p>Domicilio:
              <%= @subagencia.domicilio %></p>
            <p>Teléfono:
              <%= @subagencia.telefono %></p>
            <p>Email:
              <%= @subagencia.email %></p>

            <%= link_to 'Agregar juego impreso', new_subagencia_impreso_path([@subagencia, @impreso]) %>
            <br/>
            <%= link_to 'Listado juegos impresos', subagencia_impresos_path(@subagencia) %>
        </div>
      </div>
    </section>
  </section>